spring.datasource.url=jdbc:mysql://localhost:3306/phish?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=Shahul91235
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=your-very-long-secret-key-here-make-it-very-secure-at-least-256-bits
jwt.expiration=86400000

python.script.path=/Users/shahulhameed/phishing/python/ml/phishing_detector_fixed.py
python.executable=python3

server.port=8081
logging.level.com.phishguard=DEBUG
logging.level.root=INFO

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081
